version: "3"
services:
  ui_ms:
    build: ./ui-ms
    command: ./run.$APP_ENV.sh
    ports:
      - "8080:8080"
    volumes:
      - $volume_path/ui-ms:/opt/flix-ui
    working_dir: /opt/flix-ui
    environment:
        - NODE_ENV=$APP_ENV
  users_ms:
    build: ./users-ms
    command: ./run.$APP_ENV.sh
    ports:
      - "3030:3030"
    volumes:
      - $volume_path/users-ms:/opt/flix-users
    working_dir: /opt/flix-users
    depends_on:
      - db
    environment:
      - DB_CON=postgres://postgres:@db:5432/users_ms
      - NODE_ENV=$APP_ENV
  videos_ms:
    build: ./videos-ms
    command: ./run.$APP_ENV.sh
    ports:
      - "3032:3032"
    volumes:
      - $volume_path/videos-ms:/opt/flix-videos
    working_dir: /opt/flix-videos
    depends_on:
      - db
    environment:
      - DB_CON=postgres://postgres:password@db:5432/videos_ms
      - NODE_ENV=$APP_ENV
  rates_ms:
    build: ./rates-ms
    command: ./run.$APP_ENV.sh
    ports:
      - "3033:3033"
    volumes:
      - $volume_path/rates-ms:/opt/flix-rates
    working_dir: /opt/flix-rates
    depends_on:
      - db
    environment:
      - DB_CON=postgres://postgres:password@db:5432/rates_ms
      - NODE_ENV=$APP_ENV
  payment_ms:
    build: ./payment-ms
    command: ./run.$APP_ENV.sh
    ports:
      - "3031:3031"
    volumes:
      - $volume_path/payment-ms:/opt/flix-payment
    working_dir: /opt/flix-payment
    depends_on:
      - db
    environment:
      - DB_CON=postgres://postgres:password@db:5432/payment_ms
      - NODE_ENV=$APP_ENV
  watches_ms:
    build: ./watches-ms
    command: ./run.$APP_ENV.sh
    ports:
      - "3034:3034"
    volumes:
      - $volume_path/watches-ms:/opt/flix-watches
    working_dir: /opt/flix-watches
    depends_on:
      - db
    environment:
      - DB_CON=postgres://postgres:password@db:5432/watches_ms
      - NODE_ENV=$APP_ENV
  recommendations_ms:
    build: ./recommendations-ms
    command: ./run.$APP_ENV.sh
    ports:
      - "3035:3035"
    volumes:
      - $volume_path/recommendations-ms:/opt/flix-recommendations
    working_dir: /opt/flix-recommendations
    depends_on:
      - graph_db
    environment:
      - GDB_CON=bolt://graph_db:7687
      - GDB_USER=neo4j
      - GDB_PASS=secret
      - NODE_ENV=$APP_ENV
  graph_db:
    image: neo4j:4.0
    volumes:
      - $volume_path/graph-data:/data
    ports:
      - "7475:7474"
      - "7688:7687"
    environment:
      - NEO4J_AUTH=neo4j/secret
  db:
    image: postgres:12.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_MULTIPLE_DATABASES=users_ms,payment_ms,videos_ms,rates_ms,watches_ms
    volumes:
      - $volume_path/db-scripts:/docker-entrypoint-initdb.d
  web:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - $volume_path/nginx.$APP_ENV.conf:/etc/nginx/conf.d/default.conf
      - $volume_path/ui-ms/dist:/srv/www/static
      - $volume_path/error.nginx.log:/var/log/nginx/error.log
    depends_on:
      - users_ms
      - ui_ms
      - payment_ms
      - videos_ms
      - rates_ms
      - watches_ms
      - recommendations_ms